name: Update Data

on:
  schedule:
    - cron: '0 3 * * *' # Gira ogni notte alle 3:00
  workflow_dispatch:     # Permette l'avvio manuale con il tasto "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Aggiornato alla v4
      
      - name: Set up Python
        uses: actions/setup-python@v5 # Aggiornato alla v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase requests geopy 
          # Ho aggiunto geopy qui direttamente cos√¨ non serve il file requirements.txt
        
      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python ./script_aggiornamento.py
